name: pycon2019
channels:
  - conda-forge
  - anaconda
  - pip
dependencies:
  - python=3.6
  - jupyterlab=0.35
  - pymc3
  - mkl-service
  - matplotlib
  - pandas
  - seaborn
  - libpython
  -  m2w64-toolchain
  - pip:
    - arviz
